import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { getSession } from "@/lib/auth";
import SessionProvider from "@/providers/SessionProvider";
import { Toaster } from "@/components/ui/Sonner";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Skill Bridge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <SessionProvider session={session}>
          <main className="bg-light-97">{children}</main>
          <Toaster closeButton richColors expand={true} position="top-center" />
        </SessionProvider>
      </body>
    </html>
  );
}
